config/routes.rb
Rails.application.routes.draw do


  # get 'search/search'
  root 'home#top'
  get 'home/about'
  # get 'relationships/create'
  # get 'relationships/destroy'

  devise_for :users 

  get 'search' => 'search#search', as: 'search'
  
  resources :users, only: [:show,:index,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followers' => 'users#followers', as: 'followers'
    get 'follows' => 'users#follows', as: 'follows'
  end

  resources :books do
    resource :post_comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end
  resources :post_comments, only: [:destroy]

end

app/controllers/search_controller.rb
class SearchController < ApplicationController


  def search
    @how = params[:search][:how]
    # viewにてform_tagのsearch[how]で送られたデーターをparamsで受け取る
    @model = params[:search][:model]
    # viewにてform_tagのsearch[model]で送られたデーターをparamsで受け取る
    @content = params[:search][:content]
    # viewにてform_tagのsearch[content※ユーザー任意]で送られたデーターをparamsで受け取る
    @users = search_for(@how, @model, @content)
    @book = Book.new
  end

  private
  def match(model, content)
    if model == "user"
      User.where(name: content)
    else model == "book"
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == "user"
      User.where("name LIKE?", "#{content}%")
    else model == "book"
      Book.where("title LIKE?", "#{content}%")
    end
  end

  def backward(model, content)
    if model == "user"
      User.where("name LIKE?", "%#{content}")
    else model == "book"
      Book.hhere("title LIKE?", "%#{content}")
    end
  end

  def parrtical
    if model == "user"
      User.where("name LIKE?", "%#{content}%")
    else model == "book"
      Book.where("title LIKE?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when "match"
      match(model, content)
    when "forward"
      forward(model, content)
    when "backward"
      bacdward(model, content)
    when "partical"
      partical(model, content)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class="row">
	<div class="col-xs-3">

<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ 右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->
<h2>New Book</h2>
<%= render 'books/newform', book: @book %>
  </div>

<div class="col-xs-9">
  <% if @model == "user" %>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th></th>
					<th></th>
					<th>フォロー数</th>
					<th>フォロワー数</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
						<% if current_user != user %>
						<% if user.followed_by?(current_user) %>
								<td><%=link_to "フォロー済み", user_relationships_path(user), method: :delete %></td>
						<% else %>
								<td><%=link_to "フォローする", user_relationships_path(user), method: :post %></td>
						<% end %>
						<% else %>
						<td> </td>
					<% end %>
					<td><%= link_to user.active_relationships.count,user_follows_path(user)  %></td>
					<td><%= link_to user.followers.count, user_followers_path(user)%></td>
				</tr>
				<% end %>
			</tbody>
		</table>
  <% else @model == "book" %>
    <%= render 'books/books', books: @users %>

  <% end %>
</div>