config/routes.rb
Rails.application.routes.draw do


  # get 'search/search'
  root 'home#top'
  get 'home/about'
  # get 'relationships/create'
  # get 'relationships/destroy'

  devise_for :users 

  get 'search' => 'search#search', as: 'search'
  
  resources :users, only: [:show,:index,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followers' => 'users#followers', as: 'followers'
    get 'follows' => 'users#follows', as: 'follows'
  end

  resources :books do
    resource :post_comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end
  resources :post_comments, only: [:destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false

  has_many :books
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  
  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true,length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :baria_user, only: [:update, :edit]

  def show
		@user = User.find(params[:id])
		@books = @user.books
		@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

	def index
		@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
		@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
		
		end

		def edit
			@user = User.find(params[:id])

		end

		def update
			@user = User.find(params[:id])
			if @user.update(user_params)
				redirect_to user_path(@user), notice: "successfully updated user!"
			else
				render :edit
			end
		end

		def follows
			@user = User.find(params[:user_id])
			@usersf = @user.followings
		end

		def followers
			@user = User.find(params[:user_id])
			@users = @user.followers
		end

  private
  def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end

	#url直接防止　メソッドを自己定義してbefore_actionで発動。
		def baria_user
		unless params[:id].to_i == current_user.id
			redirect_to user_path(current_user)
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, size: '100x100', fallback: "no_image.jpg") %></tr>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
</table>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>

</div>

app/views/users/edit.html.erb
<h2>User info</h2>



<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->
<%= form_for(@user) do |f| %>

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<body>
<h1>フォローワ一覧表</h1>

<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>

    <td>フォロー数：<%= link_to @user.active_relationships.count,user_follows_path(@user)  %></td>
    <p></p>
    <td>フォローワー数：<%= link_to @user.followers.count, user_followers_path(@user)%></td>


</div>

<div class="col-xs-9">
<% @users.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>

<% end %>
</div>
</body>

app/views/users/follows.html.erb
<body>
<h1>フォロー一覧表</h1>

<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>

<td>フォロー数：<%= link_to @user.active_relationships.count,user_follows_path(@user)  %></td>
<p></p>
<td>フォローワー数：<%= link_to @user.followers.count, user_followers_path(@user)%></td>


</div>

<div class="col-xs-9">
<% @usersf.each do |user| %>
  <hr>
  <p><span>name: </span><%= link_to user.name, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
      
    <% end %>
    
<% end %>
</div>
</body>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ 右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform' , book: @book%>

	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th></th>
					<th></th>
					<th>フォロー数</th>
					<th>フォロワー数</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
						<% if current_user != user %>
						<% if user.followed_by?(current_user) %>
								<td><%=link_to "フォロー済み", user_relationships_path(user), method: :delete %></td>
						<% else %>
								<td><%=link_to "フォローする", user_relationships_path(user), method: :post %></td>
						<% end %>
						<% else %>
						<td> </td>
					<% end %>



					<td><%= link_to user.active_relationships.count,user_follows_path(user)  %></td>
					<td><%= link_to user.followers.count, user_followers_path(user)%></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

	<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
	<!--同コントローラーのviewで表示ならusersは省略可 -->

	<% if current_user != @user %>
	<% if @user.followed_by?(current_user) %>
			<p><%=link_to "フォロー済み", user_relationships_path(@user), method: :delete %></p>
	<% else %>
			<p><%=link_to "フォローする", user_relationships_path(@user), method: :post %></p>
	<% end %>
	<% end %>

	<td>フォロー数：<%=@user.active_relationships.count%></td>
	<p></p>
	<td>フォロワー数：<%=@user.followers.count%></td>

	<h2>New book</h2>
		<%= render('books/newform', book: @book) %>

	</div>

	<div class="col-xs-9">
	<h2>Books</h2>
<!--books一覧 -->
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		
			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>	
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><%= link_to "#{book.post_comments.count}件のコメント", book_path(book.id)%></td>
				<% end %>
				</tr>


			</tbody>
		</table>
	</div>
</div>
<!--books一覧 -->