config/routes.rb
Rails.application.routes.draw do


  # get 'search/search'
  root 'home#top'
  get 'home/about'
  # get 'relationships/create'
  # get 'relationships/destroy'

  devise_for :users 

  get 'search' => 'search#search', as: 'search'
  
  resources :users, only: [:show,:index,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followers' => 'users#followers', as: 'followers'
    get 'follows' => 'users#follows', as: 'follows'
  end

  resources :books do
    resource :post_comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end
  resources :post_comments, only: [:destroy]

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!

	def show
		@book = Book.find(params[:id])
		@user = @book.user
		@book_new = Book.new
		@post_comment = PostComment.new
  end

  def index
		@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
		@book = Book.new
		@user = current_user
  end

  def create
		@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
		@book.user_id = current_user.id
		if @book.save #入力されたデータをdbに保存する。
			redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
		else
			@books = Book.all
			render :index
		end
  end

	def edit
		@book = Book.find(params[:id])
		if @book.user != current_user
			redirect_to books_path
		end
  end

  def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book), notice: "successfully updated book!"
		else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
			render :edit
		end 
  end

  def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path, notice: "successfully delete book!"
  end

  private
  def book_params
		params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><%= link_to "#{book.post_comments.count}件のコメント", book_path(book.id)%></td>
						<% if book.favorited_by?(current_user) %>
					<td>
							<%= link_to book_favorites_path(book), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							<%= book.favorites.count %> 
							<% end %>
					</td>
    <% end %>

					<td>
							<%= link_to book_favorites_path(book), method: :post do %>
							<i class="fa fa-heart" aria-hidden="true"></i>
							<%= book.favorites.count %> 
							<% end %>
					<td/>
					<% end %>
				</tr>
				
			</tbody>
		</table>

app/views/books/_newform.html.erb
<% if book.errors.any? %>
	<h3><%= book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<%= flash[:notice] %>

<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>
</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ 右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><%= link_to "#{book.post_comments.count}件のコメント", book_path(book.id)%></td>
					<td>
					<div id="favorites_buttons_<%= book.id %>">
						<%= render 'favorites/favorites', book: book %>
					</div>
					</td>
<% end %>
				
			</tbody>
		</table>

		<!--books一覧 -->
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile',  user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book_new %>

	</div>

	<div class="col-xs-9">

		<h2>Book detail</h2>

		<table class="table">
			<tr>
				<td>
					<%= link_to (@book.user) do %>
					<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
					<%= @book.user.name %>
					<% end %>
				</td>
				<% if @book.user == current_user %>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				<% end %>
				</tr>
		</table>
	

<td><%= @book.post_comments.count %>件のコメント</td>

<%= form_for [@book, @post_comment] do |f|  %>

<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>

<% end %>


<% @book.post_comments.each do |p_c| %>
<a href="#" class="link-author"><%= p_c.user.name %></a>

<span class="comment-date"><%= p_c.created_at.strftime('%Y/%m/%d') %></span>

<div class="comment-entry"><%= p_c.comment %></div>

<%= link_to "Destroy",post_comment_path(p_c.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} %>
<br>
<% end %>

<div id="favorites_buttons_<%= @book.id %>">
	<%= render 'favorites/favorites', book: @book %>
</div>

</div>	
</div>